### ISSUE TITLE
Unknown issue appears when installing requirements

### ISSUE THREAD

**Issue by Javimoa95** [Fluntyy/WAPresence#1]
Hey! I was checking your projects on github and came  across WAPresence. I tried it out but as soon as I download the requirements I'm met with this issue. 

Mind giving me a hand?

[https://pastebin.com/af34fnCr](url)

Thanks!

**Comment by Fluntyy** [comment]
To install `winsdk`, first, ensure you have the Desktop Development with C++ installed via the [Visual Studio Installer](https://visualstudio.microsoft.com/). Additionally, I'm currently developing a new version that won't require `winsdk`. Stay tuned!
